using System.Text.Json.Serialization;

namespace Server.Common.Contracts;

public enum FlowNodeKind : byte
{
    Unknown = 0,
    DigitalInput = 1,
    DigitalOutput,
    DigitalConstant,
    AnalogInput,
    AnalogOutput,
    Not,
    And,
    Nand,
    Or,
    Nor,
    Xor,
    Xnor,
    Memory,
    QualityGood,
    NumericConstant,
    Add,
    Comparator,
    LevelShifter,
    OnDelay,
    RisingEdge,
    Average,
    Calculator,
    Clamp,
    Min,
    Max,
    Line,
    DigitalSwitch,
    AnalogSwitch,
    Split,
    Sequence,
    Override,
    Delay,
    Timer,
    Pulse,
    Schedule,
    Calendar,
    [JsonStringEnumMemberName("a2d")]
    A2D,
    [JsonStringEnumMemberName("d2a")]
    D2A,
    Subtract,
    Multiply,
    Divide,
    Power,
    Negate,
    Counter,
    Clock
}
