<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contracts\" />
    <Folder Include="Extensions\" />
    <Folder Include="Services\Implementation\Compiler\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Server.Common\Server.Common.csproj" />
  </ItemGroup>

</Project>
