<template>
  <AppButton text="YAML help" :icon="helpIcon" :disabled="loading" @click="open" />
  <Teleport to="body">
    <aside v-if="visible" class="guidance" aria-label="YAML configuration guidance">
      <header>
        <strong>YAML help</strong>
        <div class="guidance-actions">
          <AppButton
            text="Refresh guidance"
            :icon="refreshIcon"
            :disabled="loading"
            @click="load"
          />
          <AppButton text="Close" :icon="closeIcon" @click="close" />
        </div>
      </header>
      <p v-if="loading" role="status">Generating guidance…</p>
      <p v-else-if="error" class="request-error" role="alert">{{ error }}</p>
      <!-- Server Markdown is escaped before the small supported formatting subset is applied. -->
      <!-- eslint-disable-next-line vue/no-v-html -->
      <div v-else class="markdown" v-html="renderedMarkdown"></div>
      <section v-if="!loading && !error && guidanceYaml" class="yaml-sample">
        <AppYamlEditor
          :model-value="guidanceYaml"
          label="YAML structure for this selection"
          help="Read-only example generated by the server for the selected configuration."
          :schema="sampleSchema"
          schema-uri="app://schemas/configuration-guidance-sample.json"
          :min-height="sampleHeight"
          read-only
        />
      </section>
    </aside>
  </Teleport>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue';
import AppButton from '@/components/AppButton.vue';
import AppYamlEditor from '@/components/AppYamlEditor.vue';
import type { JSONSchema } from '@/components/yaml/MonacoYaml';
import closeIcon from '@/assets/icons/cancel-icon.svg';
import helpIcon from '@/assets/icons/info-notice-icon.svg';
import refreshIcon from '@/assets/icons/refresh-icon.svg';
import {
  fetchConfigurationGuidance,
  type ConfigurationGuidanceType
} from '@/features/configuration/api/configurationGuidanceApi';

const props = defineProps<{ type: ConfigurationGuidanceType; yaml: string; pointId?: string }>();
const markdown = ref('');
const error = ref('');
const visible = ref(false);
const loading = ref(false);
const sampleSchema: JSONSchema = {};

const yamlSectionPattern =
  /(?:^|\n)## YAML structure for this selection\s*\n+```yaml\s*\n([\s\S]*?)\n```\s*$/;
const guidanceYaml = computed(() => yamlSectionPattern.exec(markdown.value)?.[1] ?? '');
const proseMarkdown = computed(() => markdown.value.replace(yamlSectionPattern, '').trim());
const sampleHeight = computed(
  () => `${Math.min(Math.max(guidanceYaml.value.split('\n').length * 20 + 56, 260), 560)}px`
);

const escapeHtml = (value: string): string =>
  value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');

const renderedMarkdown = computed(() => {
  const inline = (value: string): string =>
    escapeHtml(value)
      .replaceAll(/`([^`]+)`/g, '<code>$1</code>')
      .replaceAll(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  const lines = proseMarkdown.value.split('\n');
  const output: string[] = [];
  let tableOpen = false;
  let codeOpen = false;
  for (const line of lines) {
    if (line.startsWith('```')) {
      if (tableOpen) {
        output.push('</tbody></table>');
        tableOpen = false;
      }
      output.push(codeOpen ? '</code></pre>' : '<pre><code>');
      codeOpen = !codeOpen;
      continue;
    }
    if (codeOpen) {
      output.push(`${escapeHtml(line)}\n`);
      continue;
    }
    if (/^\|(?:\s*:?-+:?\s*\|)+$/.test(line)) continue;
    if (line.startsWith('|')) {
      const cells = line
        .slice(1, -1)
        .split('|')
        .map((cell) => `<td>${inline(cell.trim())}</td>`);
      if (!tableOpen) {
        output.push('<table><tbody>');
        tableOpen = true;
      }
      output.push(`<tr>${cells.join('')}</tr>`);
      continue;
    }
    if (tableOpen) {
      output.push('</tbody></table>');
      tableOpen = false;
    }
    const heading = /^(#{1,3})\s+(.+)$/.exec(line);
    if (heading)
      output.push(`<h${heading[1]!.length}>${inline(heading[2]!)}</h${heading[1]!.length}>`);
    else if (line.startsWith('> '))
      output.push(`<blockquote>${inline(line.slice(2))}</blockquote>`);
    else if (line) output.push(`<p>${inline(line)}</p>`);
  }
  if (tableOpen) output.push('</tbody></table>');
  return output.join('');
});

const load = async (): Promise<void> => {
  if (loading.value) return;
  loading.value = true;
  error.value = '';
  try {
    markdown.value = await fetchConfigurationGuidance(props.type, props.yaml, props.pointId);
  } catch (reason) {
    error.value = reason instanceof Error ? reason.message : 'Unable to load guidance.';
  } finally {
    loading.value = false;
  }
};

const open = async (): Promise<void> => {
  visible.value = true;
  document.body.classList.add('configuration-guidance-open');
  await load();
};

const close = (): void => {
  visible.value = false;
  document.body.classList.remove('configuration-guidance-open');
};

onBeforeUnmount(() => {
  document.body.classList.remove('configuration-guidance-open');
});
</script>

<style scoped>
.guidance {
  position: fixed;
  z-index: 20;
  inset-block: 0;
  right: 0;
  width: min(38rem, 46vw);
  padding: var(--space-6);
  overflow: auto;
  color: var(--color-text-primary);
  background: var(--color-surface-neutral);
  border-left: var(--border-width-default) solid var(--color-border-default);
  box-shadow: var(--shadow-dialog-compact);
}
.guidance header {
  position: sticky;
  top: calc(-1 * var(--space-6));
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding-block: var(--space-3);
  background: var(--color-surface-neutral);
}
.guidance-actions {
  display: flex;
  gap: var(--space-2);
}
.markdown :deep(table) {
  width: 100%;
  border-collapse: collapse;
}
.markdown :deep(td) {
  padding: var(--space-2);
  text-align: left;
  vertical-align: top;
  border-bottom: var(--border-width-default) solid var(--color-border-default);
}
.markdown :deep(td:first-child) {
  white-space: nowrap;
}
.markdown :deep(pre) {
  padding: var(--space-4);
  overflow: auto;
  background: var(--color-surface-sunken);
}
.yaml-sample {
  margin-top: var(--space-6);
}
:global(body.configuration-guidance-open .configuration-page.editor-page) {
  margin-right: min(38rem, 46vw);
}
@media (max-width: 64rem) {
  .guidance {
    width: min(30rem, 52vw);
  }
  :global(body.configuration-guidance-open .configuration-page.editor-page) {
    margin-right: min(30rem, 52vw);
  }
}
</style>
